import { Router } from 'express';
import mongoose from 'mongoose';
import multer from 'multer';
import User from '../models/User.js';
import Document from '../models/Document.js';
import Complaint from '../models/Complaint.js';
import WorkerProfile from '../models/WorkerProfile.js';
import CustomerProfile from '../models/CustomerProfile.js';
import VerificationDocument from '../models/VerificationDocument.js';
import Booking from '../models/Booking.js';
import Job from '../models/Job.js';
import Category from '../models/Category.js';
import Skill from '../models/Skill.js';
import AuditLog from '../models/AuditLog.js';
import { auth, admin } from '../middleware/auth.js';
import { notify } from '../services/notifications.js';
import { getPrivate, putPrivate } from '../services/storage.js';
import { slugify } from '../utils/slug.js';

const r=Router(); r.use(auth,admin);
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:15*1024*1024}});
const safeUser=u=>{const x=u.toObject();delete x.passwordHash;delete x.otpHash;delete x.profileImageData;return x;};
async function audit(actor,action,entity,entityId,metadata={}){await AuditLog.create({actor,action,entity,entityId:String(entityId||''),metadata});}

r.get('/dashboard/stats',async(req,res)=>{const [totalUsers,totalWorkers,totalCustomers,pendingVerification,activeBookings,completedJobs,totalComplaints,totalDocuments,totalCategories,notifications,recentUsers,complaintsByStatus,recentComplaints,bookingOverview,topCategories,locationDistribution]=await Promise.all([User.countDocuments({role:{$ne:'admin'}}),User.countDocuments({role:'worker'}),User.countDocuments({role:'customer'}),WorkerProfile.countDocuments({verificationStatus:'pending'}),Booking.countDocuments({status:{$in:['requested','accepted','confirmed','active']}}),Booking.countDocuments({status:'completed'}),Complaint.countDocuments(),Document.countDocuments(),Category.countDocuments({active:true}),AuditLog.countDocuments({createdAt:{$gte:new Date(Date.now()-86400000)}}),User.find({role:{$ne:'admin'}}).select('name email role status createdAt profileImage profileImageData').sort({createdAt:-1}).limit(5).lean(),Complaint.aggregate([{$group:{_id:'$status',count:{$sum:1}}}]),Complaint.find().populate('user','name email').sort({createdAt:-1}).limit(5).lean(),Booking.aggregate([{$group:{_id:'$status',count:{$sum:1}}}]),Job.aggregate([{$group:{_id:'$categoryName',jobs:{$sum:1},workersNeeded:{$sum:'$workersNeeded'}}},{$sort:{jobs:-1}},{$limit:6}]),WorkerProfile.aggregate([{$match:{verificationStatus:'approved',district:{$nin:[null,'']}}},{$group:{_id:'$district',workers:{$sum:1}}},{$sort:{workers:-1}},{$limit:6}])]);const cMap=Object.fromEntries(complaintsByStatus.map(x=>[x._id,x.count]));const users=recentUsers.map(u=>{const x={...u};if(x.profileImageData?.length)x.profileImage=`/api/profile/image/${u._id}`;delete x.profileImageData;return x;});res.json({totalUsers,totalWorkers,totalCustomers,pendingVerification,activeBookings,completedJobs,totalComplaints,totalDocuments,totalCategories,notificationCount:notifications,complaintsByStatus:{pending:cMap.Submitted||0,processing:cMap['In Review']||0,resolved:cMap.Resolved||0,rejected:cMap.Rejected||0},recentComplaints,recentUsers:users,bookingOverview:bookingOverview.map(x=>({status:x._id,count:x.count})),topCategories:topCategories.map(x=>({category:x._id||'Other',jobs:x.jobs,workersNeeded:x.workersNeeded})),locationDistribution:locationDistribution.map(x=>({district:x._id,workers:x.workers}))});});
r.get('/dashboard/users-trend',async(req,res)=>{const days=Math.min(Math.max(Number(req.query.days||14),7),90);const start=new Date();start.setHours(0,0,0,0);start.setDate(start.getDate()-days+1);const rows=await User.aggregate([{$match:{role:{$ne:'admin'},createdAt:{$gte:start}}},{$group:{_id:{date:{$dateToString:{format:'%Y-%m-%d',date:'$createdAt'}},role:'$role'},count:{$sum:1}}},{$sort:{'_id.date':1}}]);const map=new Map(rows.map(x=>[`${x._id.date}:${x._id.role}`,x.count]));res.json({trend:Array.from({length:days},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const k=d.toISOString().slice(0,10);return {date:k,total:(map.get(`${k}:customer`)||0)+(map.get(`${k}:worker`)||0),workers:map.get(`${k}:worker`)||0,customers:map.get(`${k}:customer`)||0};})});});
r.get('/dashboard/complaints-trend',async(req,res)=>{const days=Math.min(Math.max(Number(req.query.days||14),7),90);const start=new Date();start.setHours(0,0,0,0);start.setDate(start.getDate()-days+1);const rows=await Complaint.aggregate([{$match:{createdAt:{$gte:start}}},{$group:{_id:{$dateToString:{format:'%Y-%m-%d',date:'$createdAt'}},count:{$sum:1}}},{$sort:{_id:1}}]);const m=new Map(rows.map(x=>[x._id,x.count]));res.json({trend:Array.from({length:days},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const k=d.toISOString().slice(0,10);return {date:k,count:m.get(k)||0};})});});
r.get('/dashboard/complaints-status',async(req,res)=>{const rows=await Complaint.aggregate([{$group:{_id:'$status',count:{$sum:1}}}]);res.json({statuses:rows.map(x=>({status:x._id,count:x.count}))});});

r.get('/users',async(req,res)=>{const q=String(req.query.q||'').trim(),status=String(req.query.status||''),role=String(req.query.role||'');const page=Math.max(Number(req.query.page||1),1),limit=Math.min(Math.max(Number(req.query.limit||20),1),100);const f={};if(q)f.$or=[{name:{$regex:q,$options:'i'}},{email:{$regex:q,$options:'i'}},{mobile:{$regex:q,$options:'i'}}];if(['active','inactive','blocked'].includes(status))f.status=status;if(['user','customer','worker','admin'].includes(role))f.role=role;const[users,total]=await Promise.all([User.find(f).select('-passwordHash -otpHash -profileImageData').sort({createdAt:-1}).skip((page-1)*limit).limit(limit),User.countDocuments(f)]);res.json({users,total,page,limit,pages:Math.ceil(total/limit)});});
r.patch('/users/:id/status',async(req,res)=>{const status=String(req.body.status||'');if(!['active','inactive','blocked'].includes(status))return res.status(400).json({message:'Invalid user status'});const u=await User.findById(req.params.id);if(!u)return res.status(404).json({message:'User not found'});if(u.role==='admin')return res.status(400).json({message:'Admin account cannot be changed here'});u.status=status;await u.save();await audit(req.user._id,'user.status','User',u._id,{status});res.json({user:safeUser(u)});});

r.patch('/users/:id/role',upload.fields([{name:'idDocument',maxCount:1},{name:'selfie',maxCount:1}]),async(req,res)=>{try{const target=await User.findById(req.params.id);if(!target)return res.status(404).json({message:'User not found'});if(target.role==='admin')return res.status(400).json({message:'Admin role cannot be changed here'});const role=String(req.body.role||'');if(!['customer','worker'].includes(role))return res.status(400).json({message:'Role must be customer or worker'});if(target.role===role)return res.status(400).json({message:`User is already a ${role}`});const files=req.files||{};if(role==='worker'){const idFile=files.idDocument?.[0];const selfie=files.selfie?.[0];const experienceYears=Number(req.body.experienceYears);if(!idFile)return res.status(400).json({message:'Aadhaar / ID document is mandatory for worker role change'});if(!selfie)return res.status(400).json({message:'Camera selfie is mandatory for worker role change'});if(!Number.isFinite(experienceYears)||experienceYears<0||experienceYears>70)return res.status(400).json({message:'Valid work experience in years is required'});if(!/^image\/(jpeg|png|webp)$/.test(selfie.mimetype))return res.status(400).json({message:'Selfie must be a JPG, PNG or WEBP image'});const idStored=await putPrivate(idFile.buffer,idFile.mimetype,idFile.originalname);target.profileImageData=selfie.buffer;target.profileImageContentType=selfie.mimetype;target.profileImage=`/api/profile/image/${target._id}`;target.role='worker';await target.save();let profile=await WorkerProfile.findOne({user:target._id});if(profile){profile.experienceYears=experienceYears;profile.verificationStatus='pending';profile.verificationRejectionReason='';await profile.save();}else{profile=await WorkerProfile.create({user:target._id,experienceYears,verificationStatus:'pending'});}await VerificationDocument.deleteMany({worker:target._id,type:'id',status:'pending'});await VerificationDocument.create({worker:target._id,type:'id',fileName:idFile.originalname,contentType:idFile.mimetype,size:idFile.size,storageKey:idStored.key,status:'pending'});await audit(req.user._id,'user.role.change','User',target._id,{from:'customer',to:'worker',experienceYears});await notify(target._id,'Worker role requested','Admin changed your role to Worker. Your Aadhaar / ID and selfie are pending verification.','verification','/worker/profile');return res.json({user:safeUser(target),profile});}
target.role='customer';await target.save();await CustomerProfile.findOneAndUpdate({user:target._id},{user:target._id},{upsert:true,new:true});await audit(req.user._id,'user.role.change','User',target._id,{from:'worker',to:'customer'});res.json({user:safeUser(target)});}catch(e){res.status(400).json({message:e.message||'Role change failed'});}});
r.delete('/users/:id',async(req,res)=>{const u=await User.findById(req.params.id);if(!u)return res.status(404).json({message:'User not found'});if(u.role==='admin')return res.status(400).json({message:'Admin cannot be deleted'});await User.deleteOne({_id:u._id});await audit(req.user._id,'user.delete','User',u._id);res.json({ok:true});});

r.get('/workers',async(req,res)=>{const status=String(req.query.status||'');const filter=status?{verificationStatus:status}:{};const profiles=await WorkerProfile.find(filter).populate('user','name email mobile profileImage profileImageData').sort({createdAt:-1}).limit(100).lean();const workers=profiles.map(p=>({...p,user:p.user?{...p.user,profileImage:p.user.profileImageData?.length?`/api/profile/image/${p.user._id}`:p.user.profileImage||''}:p.user}));workers.forEach(w=>{if(w.user)delete w.user.profileImageData});res.json({workers});});
r.get('/verification',async(req,res)=>{const status=String(req.query.status||'pending');const docs=await VerificationDocument.find(status?{status}:{}).populate('worker','name email mobile').sort({createdAt:-1}).limit(200);res.json({documents:docs});});
r.get('/verification/:id/file',async(req,res)=>{const doc=await VerificationDocument.findById(req.params.id);if(!doc)return res.status(404).end();try{const obj=doc.data?.length ? { Body: doc.data } : await getPrivate(doc.storageKey);res.set('Content-Type',doc.contentType||'application/octet-stream');res.set('Content-Disposition',`inline; filename="${encodeURIComponent(doc.fileName||'document')}"`);if (obj?.Body && typeof obj.Body.pipe === 'function') obj.Body.pipe(res);
    else if (obj?.Body instanceof Uint8Array || Buffer.isBuffer(obj?.Body)) res.end(Buffer.from(obj.Body));
    else if (obj?.Body) res.end(obj.Body);
    else res.status(404).end();}catch(e){res.status(404).end();}});
r.patch('/verification/:id',async(req,res)=>{const doc=await VerificationDocument.findById(req.params.id);if(!doc)return res.status(404).json({message:'Verification document not found'});const status=['approved','rejected','pending'].includes(req.body.status)?req.body.status:null;if(!status)return res.status(400).json({message:'Invalid status'});doc.status=status;doc.adminNote=String(req.body.adminNote||'').trim();if(status==='rejected'&&!doc.adminNote)return res.status(400).json({message:'Rejection reason is required'});await doc.save();const all=await VerificationDocument.find({worker:doc.worker});const hasRejected=all.some(d=>d.status==='rejected'),allApproved=all.length>0&&all.every(d=>d.status==='approved');const profile=await WorkerProfile.findOne({user:doc.worker});if(profile){profile.verificationStatus=hasRejected?'rejected':allApproved?'approved':'pending';profile.verificationRejectionReason=hasRejected?doc.adminNote:'';await profile.save();}await audit(req.user._id,'verification.update','VerificationDocument',doc._id,{status});await notify(doc.worker,`Verification ${status}`,status==='approved'?'Your verification document was approved.':status==='rejected'?`Your verification document was rejected. ${doc.adminNote}`:'Your document is pending review.','verification','/worker/profile');res.json({document:doc,verificationStatus:profile?.verificationStatus});});
r.patch('/workers/:id/verification',async(req,res)=>{const p=await WorkerProfile.findOne({user:req.params.id});if(!p)return res.status(404).json({message:'Worker profile not found'});const status=String(req.body.status||'');if(!['pending','approved','rejected'].includes(status))return res.status(400).json({message:'Invalid status'});const docs=await VerificationDocument.find({worker:req.params.id});if(status==='approved' && !docs.some(d=>d.type==='id' && d.status==='approved')) return res.status(400).json({message:'Approve the Aadhaar / ID document before approving the worker'});if(status==='rejected' && !String(req.body.reason||'').trim()) return res.status(400).json({message:'Rejection reason is required'});p.verificationStatus=status;p.verificationRejectionReason=String(req.body.reason||'').trim();await p.save();await audit(req.user._id,'worker.verification','WorkerProfile',p._id,{status});await notify(req.params.id,`Worker verification ${status}`,p.verificationRejectionReason||`Your verification status is now ${status}.`,'verification','/worker/profile');res.json({profile:p});});

r.get('/categories',async(req,res)=>res.json({categories:await Category.find().sort({name:1})}));
r.post('/categories',async(req,res)=>{const name=String(req.body.name||'').trim();const c=await Category.create({name,slug:slugify(name),description:req.body.description||'',icon:req.body.icon||''});res.status(201).json({category:c});});
r.patch('/categories/:id',async(req,res)=>{const c=await Category.findByIdAndUpdate(req.params.id,{$set:{...(req.body.name?{name:req.body.name,slug:slugify(req.body.name)}:{}),...(req.body.description!==undefined?{description:req.body.description}:{}),...(req.body.active!==undefined?{active:Boolean(req.body.active)}:{})}},{new:true});res.json({category:c});});
r.delete('/categories/:id',async(req,res)=>{await Skill.deleteMany({category:req.params.id});await Category.findByIdAndDelete(req.params.id);res.json({ok:true});});
r.post('/categories/:id/skills',async(req,res)=>{const name=String(req.body.name||'').trim();const s=await Skill.create({category:req.params.id,name,slug:slugify(name)});res.status(201).json({skill:s});});
r.get('/categories/:id/skills',async(req,res)=>res.json({skills:await Skill.find({category:req.params.id}).sort({name:1})}));
r.patch('/skills/:id',async(req,res)=>res.json({skill:await Skill.findByIdAndUpdate(req.params.id,req.body,{new:true})}));
r.delete('/skills/:id',async(req,res)=>{await Skill.findByIdAndDelete(req.params.id);res.json({ok:true});});

r.get('/complaints',async(req,res)=>{const f={};if(req.query.status)f.status=req.query.status;if(req.query.q)f.$or=[{subject:{$regex:req.query.q,$options:'i'}},{description:{$regex:req.query.q,$options:'i'}}];res.json({complaints:await Complaint.find(f).populate('user','name email mobile').sort({createdAt:-1}).limit(100)});});
r.patch('/complaints/:id',async(req,res)=>{const c=await Complaint.findById(req.params.id);if(!c)return res.status(404).json({message:'Complaint not found'});if(req.body.status)c.status=req.body.status;if(req.body.notes!==undefined)c.notes=req.body.notes;await c.save();res.json({complaint:await c.populate('user','name email mobile')});});


r.get('/bookings',async(req,res)=>res.json({bookings:await Booking.find().populate('customer worker','name email mobile').populate('job','title date district taluka').sort({createdAt:-1}).limit(200)}));
r.get('/jobs',async(req,res)=>res.json({jobs:await Job.find().populate('customer','name').sort({createdAt:-1}).limit(200)}));
r.get('/audit-logs',async(req,res)=>res.json({logs:await AuditLog.find().populate('actor','name email').sort({createdAt:-1}).limit(200)}));
r.post('/notifications/clear',async(req,res)=>{await AuditLog.create({actor:req.user._id,action:'admin.notifications.clear',entity:'Admin',metadata:{at:new Date()}});res.json({ok:true,clearedAt:new Date().toISOString()});});

// Existing admin document compatibility is retained. Files are stored in MongoDB GridFS.
function gridBucket(){return new mongoose.mongo.GridFSBucket(mongoose.connection.db,{bucketName:'documents'});}
async function uploadBuffer(file){const bucket=gridBucket();const id=new mongoose.Types.ObjectId();await new Promise((resolve,reject)=>{const s=bucket.openUploadStreamWithId(id,file.originalname,{contentType:file.mimetype});s.on('finish',resolve);s.on('error',reject);s.end(file.buffer);});return id;}
async function deleteFile(id){if(!id)return;try{await new Promise((resolve,reject)=>{const s=gridBucket().openDownloadStream(id);s.on('error',e=>e.code==='ENOENT'?resolve():reject(e));s.on('data',()=>{});s.on('end',resolve);});await gridBucket().delete(id);}catch{}}
function publicDocument(d){const x=d.toObject?d.toObject():d;delete x.__v;return {...x,fileUrl:x.gridFsId?`/api/admin/documents/${x._id}/download`:x.fileUrl};}
r.get('/documents',async(req,res)=>{const f={};if(req.query.q)f.$or=[{title:{$regex:req.query.q,$options:'i'}},{description:{$regex:req.query.q,$options:'i'}},{category:{$regex:req.query.q,$options:'i'}},{fileName:{$regex:req.query.q,$options:'i'}}];if(req.query.category)f.category=req.query.category;if(req.query.language)f.language=req.query.language;if(req.query.status)f.status=req.query.status;const page=Math.max(Number(req.query.page||1),1),limit=Math.min(Math.max(Number(req.query.limit||20),1),100);const[docs,total]=await Promise.all([Document.find(f).populate('uploadedBy','name email').sort({createdAt:-1}).skip((page-1)*limit).limit(limit),Document.countDocuments(f)]);res.json({documents:docs.map(publicDocument),total,page,limit,pages:Math.ceil(total/limit)});});
r.get('/documents/:id',async(req,res)=>{const d=await Document.findById(req.params.id);if(!d)return res.status(404).json({message:'Document not found'});res.json({document:publicDocument(d)});});
r.get('/documents/:id/download',async(req,res)=>{const d=await Document.findById(req.params.id);if(!d?.gridFsId)return res.status(404).end();res.set('Content-Type',d.fileContentType||'application/octet-stream');res.set('Content-Disposition',`inline; filename="${encodeURIComponent(d.fileName||'document')}"`);gridBucket().openDownloadStream(d.gridFsId).pipe(res);});
r.post('/documents',upload.fields([{name:'file',maxCount:1},{name:'thumbnail',maxCount:1}]),async(req,res)=>{const file=req.files?.file?.[0];if(!file)return res.status(400).json({message:'Document file is required'});const id=await uploadBuffer(file);const thumb=req.files?.thumbnail?.[0];const thumbId=thumb?await uploadBuffer(thumb):null;const d=await Document.create({title:req.body.title,description:req.body.description||'',category:req.body.category||'Other',documentType:req.body.documentType||'',language:req.body.language||'en',status:req.body.status||'draft',fileName:file.originalname,fileContentType:file.mimetype,fileSize:file.size,gridFsId:id,thumbnailGridFsId:thumbId,uploadedBy:req.user._id});res.status(201).json({document:publicDocument(d)});});
r.patch('/documents/:id',upload.fields([{name:'file',maxCount:1},{name:'thumbnail',maxCount:1}]),async(req,res)=>{const d=await Document.findById(req.params.id);if(!d)return res.status(404).json({message:'Document not found'});for(const f of ['title','description','category','documentType','language','status'])if(req.body[f]!==undefined)d[f]=req.body[f];const file=req.files?.file?.[0];if(file){await deleteFile(d.gridFsId);d.gridFsId=await uploadBuffer(file);d.fileName=file.originalname;d.fileContentType=file.mimetype;d.fileSize=file.size;}await d.save();res.json({document:publicDocument(d)});});
r.delete('/documents/:id',async(req,res)=>{const d=await Document.findById(req.params.id);if(!d)return res.status(404).json({message:'Document not found'});await deleteFile(d.gridFsId);await deleteFile(d.thumbnailGridFsId);await d.deleteOne();res.json({ok:true});});
export default r;
