import { Router } from 'express';
import multer from 'multer';
import Booking from '../models/Booking.js';
import Job from '../models/Job.js';
import WorkerProfile from '../models/WorkerProfile.js';
import { auth, customerOnly, workerOnly } from '../middleware/auth.js';
import { notify } from '../services/notifications.js';
import { emitToUser } from '../services/socket.js';
import { putPrivate } from '../services/storage.js';

const r=Router();
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:Number(process.env.MAX_IMAGE_SIZE_MB||5)*1024*1024}});
const populate=q=>q.populate('job').populate('customer','name mobile profileImage profileImageData').populate('worker','name mobile profileImage profileImageData');
r.get('/mine',auth,async(req,res)=>{const f=req.user.role==='worker'?{worker:req.user._id}:{customer:req.user._id};res.json({bookings:await populate(Booking.find(f).sort({createdAt:-1}))});});
r.post('/',auth,customerOnly,async(req,res)=>{try{const{jobId,workerId,notes}=req.body;const job=await Job.findOne({_id:jobId,customer:req.user._id});if(!job)return res.status(404).json({message:'Requirement not found'});const wp=await WorkerProfile.findOne({user:workerId,verificationStatus:'approved'});if(!wp)return res.status(400).json({message:'Only verified workers can be booked'});const b=await Booking.create({job:job._id,customer:req.user._id,worker:workerId,notes:String(notes||'')});await notify(workerId,'New booking request',`You have a new booking request for ${job.title}`,'booking',`/worker/bookings/${b._id}`);emitToUser(workerId,'booking:new',{bookingId:b._id});res.status(201).json({booking:await populate(Booking.findById(b._id))});}catch(e){res.status(500).json({message:e.message||'Booking request failed'});}});
r.patch('/:id/status',auth,upload.single('selfie'),async(req,res)=>{const b=await Booking.findById(req.params.id).populate('job');if(!b)return res.status(404).json({message:'Booking not found'});const next=String(req.body.status||'');if(req.user.role==='worker'&&String(b.worker)!==String(req.user._id))return res.status(403).json({message:'Not your booking'});if(req.user.role!=='worker'&&String(b.customer)!==String(req.user._id))return res.status(403).json({message:'Not your booking'});const allowed=req.user.role==='worker'?['accepted','rejected','active','completed','cancelled']:['confirmed','cancelled','completed'];if(!allowed.includes(next))return res.status(400).json({message:'Invalid booking transition'});b.status=next;if(next==='active')b.startedAt=new Date();if(next==='completed')b.completedAt=new Date();if(next==='cancelled')b.cancelledAt=new Date();if(req.body.agreedAmount!==undefined&&req.user.role==='customer')b.agreedAmount=Number(req.body.agreedAmount);if(next==='active'&&req.user.role==='worker'){if(!req.file)return res.status(400).json({message:'A fresh camera selfie is required before starting work'});if(req.file.mimetype!=='image/jpeg'&&req.file.mimetype!=='image/png'&&req.file.mimetype!=='image/webp')return res.status(400).json({message:'Selfie must be an image'});const stored=await putPrivate(req.file.buffer,req.file.mimetype,req.file.originalname);b.arrivalSelfieKey=stored.key;b.arrivalSelfieName=req.file.originalname;b.arrivalSelfieContentType=req.file.mimetype;b.arrivalSelfieSize=req.file.size;}await b.save();const target=req.user.role==='worker'?b.customer:b.worker;await notify(target,`Booking ${next}`,`Booking ${b.job?.title||'work'} is now ${next}.`,'booking',`/bookings/${b._id}`);emitToUser(target,'booking:update',{bookingId:b._id,status:next});res.json({booking:await populate(Booking.findById(b._id))});});
r.patch('/:id/complete',auth,async(req,res)=>{const b=await Booking.findById(req.params.id);if(!b)return res.status(404).json({message:'Booking not found'});const field=req.user.role==='worker'?'workerConfirmedCompletion':'customerConfirmedCompletion';if(String(b[field==='workerConfirmedCompletion'?'worker':'customer'])!==String(req.user._id))return res.status(403).json({message:'Not your booking'});b[field]=true;if(b.customerConfirmedCompletion&&b.workerConfirmedCompletion)b.status='completed';await b.save();res.json({booking:b});});
export default r;
