import {Router} from 'express'; import Complaint from '../models/Complaint.js'; import {auth,admin} from '../middleware/auth.js';
import { notify } from '../services/notifications.js';
import { emitToUser } from '../services/socket.js';
const r=Router(); const id=()=>`WF-${new Date().getFullYear()}-${Math.random().toString(36).slice(2,8).toUpperCase()}`;
r.get('/',auth,async(req,res)=>res.json({complaints:await Complaint.find({user:req.user._id}).sort({createdAt:-1})}));
r.post('/',auth,async(req,res)=>{const{subject,description,category}=req.body;if(!subject||!description)return res.status(400).json({message:'Subject and description are required'});const c=await Complaint.create({complaintId:id(),user:req.user._id,subject,description,category});res.status(201).json({complaint:c})});
r.get('/track/:complaintId',async(req,res)=>{const c=await Complaint.findOne({complaintId:req.params.complaintId});if(!c)return res.status(404).json({message:'Complaint not found'});res.json({complaint:c})});
r.get('/admin/all',auth,admin,async(req,res)=>res.json({complaints:await Complaint.find().populate('user','name email mobile').sort({createdAt:-1})}));
r.patch('/admin/:id',auth,admin,async(req,res)=>{const c=await Complaint.findById(req.params.id);if(!c)return res.status(404).json({message:'Complaint not found'});const nextStatus=String(req.body.status||c.status);if(!['Submitted','In Review','Resolved','Rejected'].includes(nextStatus))return res.status(400).json({message:'Invalid complaint status'});const previousStatus=c.status;c.status=nextStatus;if(req.body.notes!==undefined)c.notes=String(req.body.notes||'');await c.save();if(previousStatus!==c.status||req.body.notes!==undefined){const title=`Complaint ${c.complaintId} updated`;const message=c.status==='Resolved'?'Your complaint has been resolved.':c.status==='Rejected'?'Your complaint has been rejected.':c.status==='In Review'?'Your complaint is now under review.':'Your complaint is pending review.';const notification=await notify(c.user,title,message,'complaint','/complaints');emitToUser(c.user,'complaint:updated',{complaint:c,notification});}res.json({complaint:c})}); export default r;
