import { Router } from 'express';
import multer from 'multer';
import Job from '../models/Job.js';
import Application from '../models/Application.js';
import Category from '../models/Category.js';
import Skill from '../models/Skill.js';
import WorkerProfile from '../models/WorkerProfile.js';
import Booking from '../models/Booking.js';
import { auth, customerOnly, workerOnly } from '../middleware/auth.js';
import { notify } from '../services/notifications.js';
import { getPrivate, putPrivate } from '../services/storage.js';

const r=Router();
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:Number(process.env.MAX_IMAGE_SIZE_MB||5)*1024*1024}});
const populateJob=q=>q.populate('category','name slug').populate('skills','name').populate('customer','name');

r.post('/',auth,customerOnly,upload.single('image'),async(req,res)=>{try{const body=req.body||{};const skills=Array.isArray(body.skills)?body.skills:(body.skills?JSON.parse(body.skills):[]);const{title,description,category,workersNeeded,date,startTime,endTime,district,taluka,locality,address,budget,specialRequirements}=body;if(!title||!category||!date||!district)return res.status(400).json({message:'Title, category, date and district are required'});const c=await Category.findById(category);if(!c)return res.status(400).json({message:'Invalid category'});const skillDocs=await Skill.find({_id:{$in:skills}});let imageData={};if(req.file){const stored=await putPrivate(req.file.buffer,req.file.mimetype,req.file.originalname);imageData={imageKey:stored.key,imageName:req.file.originalname,imageContentType:req.file.mimetype,imageSize:req.file.size};}const job=await Job.create({customer:req.user._id,title,description,category:c._id,categoryName:c.name,skills:skillDocs.map(s=>s._id),skillNames:skillDocs.map(s=>s.name),workersNeeded:Math.max(1,Number(workersNeeded)||1),date,startTime,endTime,district,taluka,locality,address,budget:budget===undefined||budget===''?null:Number(budget),specialRequirements,...imageData});res.status(201).json({job:await populateJob(Job.findById(job._id))});}catch(e){res.status(400).json({message:e.message||'Unable to create requirement'});}});
r.get('/',async(req,res)=>{const{q,category,district,taluka,status='open',skill}=req.query;const f={status};if(category)f.category=category;if(district)f.district=new RegExp(String(district),'i');if(taluka)f.taluka=new RegExp(String(taluka),'i');if(skill)f.skillNames={$in:[new RegExp(String(skill),'i')]};let jobs=await populateJob(Job.find(f).sort({date:1,createdAt:-1}).limit(100));if(q)jobs=jobs.filter(j=>`${j.title} ${j.description} ${j.categoryName} ${(j.skillNames||[]).join(' ')}`.toLowerCase().includes(String(q).toLowerCase()));res.json({jobs});});
r.get('/mine',auth,customerOnly,async(req,res)=>{const jobs=await populateJob(Job.find({customer:req.user._id}).sort({createdAt:-1}));const ids=jobs.map(j=>j._id);const apps=ids.length?await Application.find({job:{$in:ids}}).populate('worker','name profileImage').sort({createdAt:-1}).lean():[];const profiles=apps.length?await WorkerProfile.find({user:{$in:apps.map(a=>a.worker?._id).filter(Boolean)}}).lean():[];const pmap=new Map(profiles.map(p=>[String(p.user),p]));const grouped=new Map();for(const a of apps){const x={...a,worker:{...(a.worker||{}),profile:pmap.get(String(a.worker?._id))||null}};const k=String(a.job);if(!grouped.has(k))grouped.set(k,[]);grouped.get(k).push(x);}res.json({jobs:jobs.map(j=>({...j.toObject(),applications:grouped.get(String(j._id))||[]}))});});
r.get('/applications/mine',auth,workerOnly,async(req,res)=>res.json({applications:await Application.find({worker:req.user._id}).populate({path:'job',populate:[{path:'customer',select:'name'},{path:'category',select:'name'}]}).sort({createdAt:-1})}));
r.post('/:id/apply',auth,workerOnly,async(req,res)=>{try{const job=await Job.findById(req.params.id);if(!job||job.status!=='open')return res.status(404).json({message:'Open job not found'});const p=await WorkerProfile.findOne({user:req.user._id});if(!p||p.verificationStatus!=='approved')return res.status(403).json({message:'Your worker verification must be approved before applying'});const app=await Application.create({job:job._id,worker:req.user._id,note:String(req.body.note||'')});await notify(job.customer,'New worker application',`${req.user.name} applied for ${job.title}`,'application','/requests');res.status(201).json({application:app});}catch(e){res.status(e.code===11000?409:500).json({message:e.code===11000?'You already applied for this job':e.message||'Application failed'});}});
r.patch('/applications/:id/withdraw',auth,workerOnly,async(req,res)=>{const app=await Application.findOne({_id:req.params.id,worker:req.user._id});if(!app)return res.status(404).json({message:'Application not found'});if(!['pending'].includes(app.status))return res.status(400).json({message:'Only pending applications can be withdrawn'});app.status='withdrawn';await app.save();res.json({application:app});});
r.patch('/applications/:id',auth,customerOnly,async(req,res)=>{const app=await Application.findById(req.params.id).populate('job');if(!app||String(app.job.customer)!==String(req.user._id))return res.status(404).json({message:'Application not found'});const status=['accepted','rejected'].includes(req.body.status)?req.body.status:null;if(!status)return res.status(400).json({message:'Invalid application status'});app.status=status;await app.save();let booking=null;if(status==='accepted'){booking=await Booking.findOne({job:app.job._id,worker:app.worker});if(!booking){booking=await Booking.create({job:app.job._id,customer:req.user._id,worker:app.worker,status:'accepted'});}await notify(app.worker,'Worker application accepted',`Your application for ${app.job.title} was accepted. Booking created.`,'booking',`/worker/bookings/${booking._id}`);}else{await notify(app.worker,`Application ${status}`,`Your application for ${app.job.title} was ${status}.`,'application','/worker/applications');}res.json({application:app,booking});});
r.get('/:id/image',async(req,res)=>{const job=await Job.findById(req.params.id).select('imageKey imageName imageContentType customer');if(!job?.imageKey)return res.status(404).end();const object=await getPrivate(job.imageKey);res.setHeader('Content-Type',job.imageContentType||'application/octet-stream');res.setHeader('Content-Disposition',`inline; filename="${String(job.imageName||'requirement').replace(/"/g,'')}"`);if(object?.Body?.pipe)return object.Body.pipe(res);if(Buffer.isBuffer(object?.Body))return res.end(object.Body);if(object?.Body?.transformToByteArray)return res.end(Buffer.from(await object.Body.transformToByteArray()));return res.status(404).end();});
r.get('/:id',async(req,res)=>{const job=await populateJob(Job.findById(req.params.id));if(!job)return res.status(404).json({message:'Job not found'});res.json({job});});
export default r;
