import { Router } from 'express';
import multer from 'multer';
import WorkerProfile from '../models/WorkerProfile.js';
import User from '../models/User.js';
import Skill from '../models/Skill.js';
import Category from '../models/Category.js';
import VerificationDocument from '../models/VerificationDocument.js';
import Review from '../models/Review.js';
import FavoriteWorker from '../models/FavoriteWorker.js';
import { auth, customerOnly, workerOnly } from '../middleware/auth.js';
import { putPrivate, getPrivate } from '../services/storage.js';
import { notify } from '../services/notifications.js';

const r=Router();
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:15*1024*1024}});
const publicWorker=async(p)=>{const u=p.user?.name?p.user:await User.findById(p.user).select('name profileImage profileImageData mobile');return {id:u?._id,name:u?.name,profileImage:u?.profileImageData?.length?`/api/profile/image/${u._id}`:u?.profileImage||'',profession:p.headline,headline:p.headline,bio:p.bio,skills:p.skillNames,district:p.district,taluka:p.taluka,city:p.city,area:p.area,locality:p.locality,experienceYears:p.experienceYears,languages:p.languages,availability:p.availability,verificationStatus:p.verificationStatus,rating:p.ratingAverage,ratingCount:p.ratingCount,completedJobs:p.completedJobs,responseRate:p.responseRate,joinedAt:p.joinedAt,portfolio:p.portfolio?.map(x=>({title:x.title,description:x.description,imageUrl:x.imageUrl||''})),contactAvailable:false};};

r.get('/me',auth,workerOnly,async(req,res)=>{const p=await WorkerProfile.findOne({user:req.user._id}).populate('skills','name').populate('user','name profileImage profileImageData');if(!p)return res.status(404).json({message:'Worker profile not found'});const profile=p.toObject();profile.profileImage=p.user?.profileImageData?.length?`/api/profile/image/${req.user._id}`:p.user?.profileImage||'';delete profile.user?.profileImageData;res.json({profile});});
r.patch('/me',auth,workerOnly,async(req,res)=>{const allowed=['headline','bio','experienceYears','district','taluka','city','area','locality','languages','availability','skillNames'];const p=await WorkerProfile.findOneAndUpdate({user:req.user._id},{$set:Object.fromEntries(allowed.filter(k=>req.body[k]!==undefined).map(k=>[k,req.body[k]]))},{new:true,upsert:true});res.json({profile:p});});
r.post('/me/documents',auth,workerOnly,upload.single('file'),async(req,res)=>{try{if(!req.file)return res.status(400).json({message:'Document file is required'});const type=['id','experience_certificate','skill_certificate','other'].includes(req.body.type)?req.body.type:'other';const stored=await putPrivate(req.file.buffer,req.file.mimetype,req.file.originalname);const doc=await VerificationDocument.create({worker:req.user._id,type,fileName:req.file.originalname,contentType:req.file.mimetype,size:req.file.size,storageKey:stored.key});await WorkerProfile.updateOne({user:req.user._id},{verificationStatus:'pending'});res.status(201).json({document:{id:doc._id,type:doc.type,fileName:doc.fileName,status:doc.status}});}catch(e){res.status(500).json({message:e.message||'Document upload failed'});}});
r.get('/me/documents',auth,workerOnly,async(req,res)=>res.json({documents:await VerificationDocument.find({worker:req.user._id}).select('-storageKey').sort({createdAt:-1})}));
r.get('/favorites',auth,customerOnly,async(req,res)=>{const rows=await FavoriteWorker.find({customer:req.user._id}).select('worker').lean();res.json({workerIds:rows.map(x=>String(x.worker))});});
r.patch('/:id/favorite',auth,customerOnly,async(req,res)=>{const worker=await User.findById(req.params.id).select('_id role');if(!worker||worker.role!=='worker')return res.status(404).json({message:'Worker not found'});const existing=await FavoriteWorker.findOne({customer:req.user._id,worker:worker._id});if(existing){await existing.deleteOne();return res.json({favorite:false});}await FavoriteWorker.create({customer:req.user._id,worker:worker._id});res.json({favorite:true});});
r.get('/search',async(req,res)=>{try{const{q,category,skill,district,taluka,experienceMin,ratingMin,availability,languages,verified}=req.query;const filter={verificationStatus:'approved'};if(district)filter.district=new RegExp(String(district),'i');if(taluka)filter.taluka=new RegExp(String(taluka),'i');if(availability)filter.availability=availability;if(experienceMin)filter.experienceYears={$gte:Number(experienceMin)};if(ratingMin)filter.ratingAverage={$gte:Number(ratingMin)};if(skill)filter.skillNames={$in:[new RegExp(String(skill),'i')]};if(category){const c=await Category.findOne({$or:[{_id:category},{slug:String(category).toLowerCase()}]});if(c){const skills=await Skill.find({category:c._id}).select('name');filter.skillNames={$in:skills.map(s=>new RegExp(`^${s.name}$`,'i'))};}}let profiles=await WorkerProfile.find(filter).populate('user','name profileImage profileImageData').sort({ratingAverage:-1,completedJobs:-1}).limit(50);if(q)profiles=profiles.filter(p=>`${p.user?.name} ${p.headline} ${(p.skillNames||[]).join(' ')}`.toLowerCase().includes(String(q).toLowerCase()));res.json({workers:await Promise.all(profiles.map(publicWorker))});}catch(e){res.status(500).json({message:e.message||'Unable to search workers'});}});
r.get('/:id',async(req,res)=>{const p=await WorkerProfile.findOne({user:req.params.id,verificationStatus:'approved'}).populate('user','name profileImage profileImageData').populate('skills','name');if(!p)return res.status(404).json({message:'Verified worker not found'});const reviews=await Review.find({worker:req.params.id}).populate('customer','name').sort({createdAt:-1}).limit(10).lean();res.json({worker:await publicWorker(p),reviews});});
export default r;
